-- Combined TIC-80 cartridge file
-- Generated by combine.lua

-- BEGIN enum.lua
--source: https://raw.githubusercontent.com/Keyslam/Enum/master/enum.lua

local Enum = {}
local Meta = {
   __index    = function(_, k) error("Attempt to index non-existant enum '"..tostring(k).."'.", 2) end,
   __newindex = function()     error("Attempt to write to static enum", 2) end,
}

function Enum.new(...)
   local values = {...}

   if type(values[1]) == "table" then
      values = values[1]
   end

   local enum = {}

   for i = 1, #values do
      enum[values[i]] = values[i]
   end

   return setmetatable(enum, Meta)
end

Enum = setmetatable(Enum, {
   __call  = function(_, ...) return Enum.new(...) end,
})

local Set = {}

function Set:new (list)
   o = {set = {}}
   setmetatable(o, self)
   self.__index = self

   for _, l in ipairs(list) do o.set[l] = true end
  return o
end

function Set:to_list()
  local keys={}
  for key,_ in pairs(self.set) do
    table.insert(keys, key)
  end
  return keys
end

function Set:compare(other)
    -- Check if all elements in set A are in set B
    for key in pairs(self.set) do
        if other.set[key] ~= true then
            return false -- A key in set A is not in set B
        end
    end

    -- Check if all elements in set B are in set A
    for key in pairs(other.set) do
        if self.set[key] ~= true then
            return false -- A key in set B is not in set A
        end
    end

    return true -- All keys matched in both sets
end

function Set.__eq(a, b)
   -- Check if all elements in set A are in set B
   local ret = a:compare(b)
   print("S_e: " .. tostring(ret))
   return ret
end
-- END set.lua

-- BEGIN pt.lua
local Pt = {}
local points = {}
setmetatable(points, {__mode = "v"})  -- make values weak

function Pt:new (x, y)
   local key
   if type(x) == "table" then
      key = x.x .. "-" .. x.y
   else
      key = x .. "-" .. y
   end

   if points[key] then return points[key] end


   o = {}
   setmetatable(o, self)
   self.__index = self
   -- print('PT:n')

   -- print('PT tx: ' .. type(x))
   -- print('PT ty: ' .. type(y))
   if type(x) == "table" then
      o.x = x.x
      o.y = x.y
   else
      o.x = x or 0
      o.y = y or 0
   end

   points[key] = o

   return o
end

function Pt:toarray()
   return {self.x, self.y}
end

function Pt.__eq(a, b)
   -- Check if all elements in set A are in set B

   print('PT_e at: ' .. type(a))
   print('PT_e bt: ' .. type(b))

   if type(a) ~= "table" or type(b) ~= "table" then
      print("NT")
      return false
   end

   return a.x == b.x and a.y == b.y
end

function Pt:__tostring()
   return "Pt{" .. self.x .. ", " .. self.y .. "}"
end
-- END pt.lua

-- BEGIN events.lua
------------------------------------------------------------------------------
-- EventEmitter Class in Node.js Style
-- LICENSE: MIT
-- Simen Li <simenkid@gmail.com>
-- Original Source: https://raw.githubusercontent.com/simenkid/lua-events/master/events_simplified.lua
------------------------------------------------------------------------------

local PFX = '_n_'
local PFX_LEN = #PFX
local Events = {}

local function rm(tbl, pred)
    if (pred == nil) then return tbl end
    local x, len = 0, #tbl
    for i = 1, len do
        local trusy, idx = false, (i - x)
        if (type(pred) == 'function') then trusy = pred(tbl[idx])
        else trusy = tbl[idx] == pred
        end

        if (trusy) then
            table.remove(tbl, idx)
            x = x + 1
        end
    end
    return tbl
end

function Events:new(obj)
    obj = obj or {}
    self.__index = self
    setmetatable(obj, self)
    obj._on = {}

    return obj
end

function Events:_evtb(ev)
    self._on[ev] = self._on[ev] or {}
    return self._on[ev]
end

-- ************************************************************************ --
-- ** Public APIs                                                         * --
-- ************************************************************************ --
function Events:on(ev, listener)
   local key = PFX .. tostring(ev)
   trace("on " .. key)

    if table.unpack then
       trace('up')
    else
       trace('np')
    end


    table.insert(self:_evtb(key), listener)
    return self
end

function Events:emit(ev, ...)
    local pfx_ev, argus = PFX .. tostring(ev), {...}
    local evtbl = self._on[pfx_ev]

    trace('a ')
    tprint(argus)

    local function exec(tbl)
       for n, lsn in ipairs(tbl) do
	  trace('n ' .. n)
	  local status, err = pcall(lsn, table.unpack(argus))
	  if not (status) then
	     trace(n .. " emit error: " .. tostring(err))
	  end
        end
    end

    if (evtbl ~= nil) then exec(evtbl) end

    -- one-time listener
    pfx_ev = pfx_ev .. ':_'
    evtbl = self._on[pfx_ev]

    if (evtbl ~= nil) then
        exec(evtbl)
        rm(evtbl, function (v) return v ~= nil  end)
        self._on[pfx_ev] = nil
    end
    return self
end

function Events:once(ev, listener)
    table.insert(self:_evtb(PFX .. tostring(ev) .. ':_'), listener)
    return self
end

function Events:removeAll(ev)
    if ev ~= nil then
        local pfx_ev = PFX .. tostring(ev)
        local evtbl = self:_evtb(pfx_ev)
        rm(evtbl, function (v) return v ~= nil  end)

        pfx_ev = pfx_ev .. ':_'
        evtbl = self:_evtb(pfx_ev)
        rm(evtbl, function (v) return v ~= nil  end)
        self._on[pfx_ev] = nil
    else
        for _pfx_ev, _t in pairs(self._on) do self:removeAll(string.sub(_pfx_ev, PFX_LEN + 1)) end
    end

    for _pfx_ev, _t in pairs(self._on) do
        if (#_t == 0) then self._on[_pfx_ev] = nil end
    end

    return self
end

function Events:remove(ev, listener)
    local pfx_ev = PFX .. tostring(ev)
    local evtbl = self:_evtb(pfx_ev)
    local lsnCount = 0
    -- normal listener
    rm(evtbl, listener)
    if (#evtbl == 0) then self._on[pfx_ev] = nil end

    -- emit-once listener
    pfx_ev = pfx_ev .. ':_'
    evtbl = self:_evtb(pfx_ev)
    rm(evtbl, listener)
    if (#evtbl == 0) then self._on[pfx_ev] = nil end

    return self
end
-- END events.lua

-- BEGIN grid.lua
local Grid = {height=GRID_HEIGHT, width=GRID_WIDTH}

function Grid:new (w, h)
   o = {   height = h,
	   width = w,
	   tile_cnt=0
   }
   setmetatable(o, self)
   self.__index = self

   for y=1, h do
      o[y] = {}
      for x=1, w do
	 o[y][x] = 0
      end
   end

   return o
end

function Grid:init(tile_cnt)
   self.tile_cnt = tile_cnt
   for y=1, self.height do
      for x=1, self.width do
	 local r =  math.random(1, tile_cnt) -- Six types of tiles
	 --       trace("new tile: " .. r .. " " .. x .. " " .. y)
	 self[y][x] = r
      end
   end
end


function Grid:test()
   for y=1, self.height do
      for x=1, self.width do
	 local r = self[y][x]
	 --     trace("test tile: " .. r .. " " .. x .. " " .. y)
	 assert (r ~= 0)

      end
   end
end

function Grid:find_matches()
  local matches = {}
  for y=1, self.height do
    for x=1, self.width do
      local tile = self[y][x]
      if x <= self.width - 2 and self[y][x+1] == tile and self[y][x+2] == tile then
        table.insert(matches, Pt:new(x,y))
	table.insert(matches, Pt:new{x=x+1, y=y})
	table.insert(matches, Pt:new{x=x+2, y=y})
      end
      if y <= self.height - 2 and self[y+1][x] == tile and self[y+2][x] == tile then
	 table.insert(matches, Pt:new{x=x, y=y})
	 table.insert(matches, Pt:new{x=x, y=y+1})
	 table.insert(matches, Pt:new{x=x, y=y+2})
      end
    end
  end

  match_set = Set:new(matches)
  return match_set:to_list()
end

function Grid:remove_cell(p)
   for y=p.y, 2, -1 do
--      trace('rc: ' .. p.x .. " " .. y)
      self[y][p.x] = self[y-1][p.x]
   end
   local r = math.random(1, self.tile_cnt)
--   trace('nc: ' .. p.x .. " " .. 1 .. " " .. r)
   self[1][p.x] = r
end

-- Remove matches and fill the grid
function Grid:remove_matches(matches)
 for _, match in ipairs(matches) do
    self:remove_cell(match)
 end
end

function Grid:get(p)
   return self[p.y][p.x]
end

function Grid:set(p, v)
   self[p.y][p.x] = v
end

function Grid:allow_swap(a, b)
   if not self:are_adjacent(a, b) then
      return {false, {}}
   end
   self:swap(a, b)
   local matches = self:find_matches()
   print("Gas m: " .. #matches)
   self:swap(a, b)
   if #matches > 0 then
      return {true, matches}
   end
   return {false, {}}
end

-- Swap tiles
function Grid:swap(a, b)
   local temp = self:get(a)
   self[a.y][a.x] = self:get(b)
   self[b.y][b.x] = temp
end

-- Check if two tiles are adjacent
function Grid:are_adjacent(a, b)
 return math.abs(a.x - b.x) + math.abs(a.y - b.y) == 1
end
-- END grid.lua

-- BEGIN mc_lib.lua
-- Constants
PLAY_WIDTH = 110
PLAY_HEIGHT = 126
MISSILE_SPEED = 0.125
BULLET_SPEED = 0.5

-- Classes

Missile = {
   x = 0,
   y = 0,
   target_x = 0,
   target_y = 0,
   speed = 0
}

function Missile:new (o)
   o = o or {   x = 0,
   y = 0,
   target_x = 0,
   target_y = 0,
   speed = 0
}
   setmetatable(o, self)
   self.__index = self
   return o
end

function Missile:update()
   self.y = self.y + self.speed
end

-- Variables

MC_Game = {}

function MC_Game:new ()
   o =  {
      missiles = {},
      bullets = {},
      explosions = {},
      score = 0,
      game_over = false,
      last_add = 0,
      particles = {},
   }
   setmetatable(o, self)
   self.__index = self
   return o
end

function MC_Game:missiles_add ()
    local missile = Missile:new({
        x = math.random(0, PLAY_WIDTH),
        y = 0,
        target_x = math.random(0, PLAY_WIDTH),
        target_y = PLAY_HEIGHT-10,
        speed = MISSILE_SPEED
    })
    table.insert(self.missiles, missile)
    trace("Current missiles: ")
    for i, missile in ipairs(self.missiles) do
       trace(i .. " " .. missile.x .. " " .. missile.y)
    end
    self.last_add = time()
end

function MC_Game:missiles_draw()
   for i, missile in ipairs(self.missiles) do
      spr(19, missile.x, missile.y, 0, 1, 0, 0,1,1)
      -- print(missile.x .. "," .. math.floor(missile.y),
      -- 	    missile.x+10, missile.y, 12)
   end
end

function MC_Game:missiles_update()
    for i, missile in ipairs(self.missiles) do
       missile:update()
       if missile.y >= missile.target_y then
	  self.score = self.score - 1
	  if self.score < 0 then
	     self.score = 0
	  end
	  table.remove(self.missiles, i)
	  table.insert(self.particles, new_part({x = missile.x,
						 y = missile.y}))

       end
    end
end

function MC_Game:init(events)
   trace("MC_Game:init")
   self.events = events
   self.events:on('bullet', function()
		     local m = self.missiles[1]
		     trace("NextM: " .. m.x .. " " .. m.y)
		     self:add_bullet(m.x+4, PLAY_HEIGHT - 10)
		     end
		     )
   --for i = 1, 3 do
   self:missiles_add()
   -- end
end

function MC_Game:add_bullet(x, y)
   trace("Add bullet")
    local bullet = {
        x = x,
        y = y,
        speed = BULLET_SPEED
    }
    table.insert(self.bullets, bullet)
end

function MC_Game:update()
    if self.game_over then return end

    -- Update missiles
    self:missiles_update()

    if time() - self.last_add > 5000 then
       self:missiles_add()
    end

    -- Update bullets
    for i, bullet in ipairs(self.bullets) do
        bullet.y = bullet.y - bullet.speed
    end

    -- Check collisions
    for i = #self.bullets, 1, -1 do
        local bullet = self.bullets[i]
        for j, missile in ipairs(self.missiles) do
            if math.abs(bullet.x - missile.x) < 7 and math.abs(bullet.y - missile.y) < 5 then
	       trace("BH!")
	       table.insert(self.particles, new_part({x = missile.x,
						      y = missile.y}))
	       table.remove(self.bullets, i)
	       table.remove(self.missiles, j)
                self.score = self.score + 1
                break
            end
        end
    end

    -- Remove off-screen bullets
    for i = #self.bullets, 1, -1 do
        if self.bullets[i].y < 0 then
            table.remove(self.bullets, i)
        end
    end
end

local part_sprs = {66, 67, 68}

function new_part(p)
   return {
      x=p.x,
      y=p.y,
      life=60
   }
end

function MC_Game:draw()
   map(0, 0, 30, 30, 0, 0, -1, 1, nil)
   if game_over then
      local text_x = PLAY_WIDTH // 2 - 30
      print("Game Over", text_x, PLAY_HEIGHT // 2 - 6, 12)
      print("Score: " .. MC_Game.score, text_x, PLAY_HEIGHT // 2 + 6, 12)
   else
      self:missiles_draw()

      for i, bullet in ipairs(self.bullets) do
	 rect(bullet.x, bullet.y, 1, bullet.y, 12)
	 --print(bullet.x .. "," .. math.floor(bullet.y), bullet.x+5, bullet.y, 12)
      end
      print("Score: " .. self.score, 125, 130, 12)
   end

   if #self.particles > 0 then
      -- trace('drawing mc particles: ' .. #self.particles)
      for i, m in pairs(self.particles) do
	 local orig_x = m.x
	 local orig_y = m.y
	 local part_num =  mod(m.life, 20)
	 local tile_grp = part_sprs[m.life]
	 --trace(tile .. " " .. tile_grp)
	 spr(tile_grp, orig_x, orig_y, 0, 1, 0, 0,1,1)
	 m.life = m.life -1
	 if m.life == 0 then
	    table.remove(self.particles, i)
	 end
      end
   end

end
-- END mc_lib.lua

-- BEGIN m3_lib.lua

-- Constants
TILE_SIZE = 16
GRID_WIDTH = 7
GRID_HEIGHT = 8

-- Select mode is moving the select around.
-- swap mode is picking a direction to swap two tiles.
InputModes = Enum("Select", "Swap")

M3_Game = {}

function M3_Game:new ()
   o = {
      grid = Grid:new(GRID_WIDTH, GRID_HEIGHT),
      selected = Pt:new{x = math.ceil(grid.width/2), y = grid.height/2},
      input_mode = InputModes.Select,
      particles = {},
   }
   setmetatable(o, self)
   self.__index = self
   return o
end

-- Variables
grid = Grid:new(GRID_WIDTH, GRID_HEIGHT) --{height=GRID_HEIGHT, width=GRID_WIDTH}

function tprint (tbl, indent)
  if not indent then indent = 0 end
  for k, v in pairs(tbl) do
    formatting = string.rep("  ", indent) .. k .. ": "
    if type(v) == "table" then
      trace(formatting)
      tprint(v, indent+1)
    elseif type(v) == 'boolean' then
      trace(formatting .. tostring(v))
    elseif type(v) == 'function' then
      trace(formatting .. "func")
    else
      trace(formatting .. v)
    end
  end
end

local part_sprs = {5, 7, 9, 11}

tile_sprs = {
   160,
   162,
   192,
   194,
   224,
   226,
}
trace("TS:")
tprint(tile_sprs, 2)

function new_part(p)
   return {
      x=p.x,
      y=p.y,
      life=12
   }
end

-- Draw the grid
function M3_Game:grid_draw()
   -- trace("gd")
   -- tprint(self.grid, 1)
   self.grid:test()
   for y=1, self.grid.height do
      for x=1, self.grid.width do
	 local tile = self.grid[y][x]
	 local orig_x = (x-1)*TILE_SIZE
	 local orig_y = (y-1)*TILE_SIZE
	 --trace(y .. ' ' ..  x .. ' ' .. tile)
	 local tile_grp = tile_sprs[tile]
	 --trace(tile .. " " .. tile_grp)
	 spr(tile_grp, orig_x+120, orig_y, 1, 1, 0, 0,2,2)

	 if self.selected.x == x and self.selected.y == y then
	    local color = 13
	    --trace("selected: " .. x .. " " .. y .. " " .. self.grid[y][x] .. " " .. tile_sprs[self.grid[y][x]])
	    if self.input_mode == InputModes.Swap then
	       color = 4
	    end
	    rectb(orig_x+120, orig_y, TILE_SIZE, TILE_SIZE, color)

	 end
      end
   end
end

-- Select tile
function M3_Game:select_tile(dx, dy)
   local new_x = self.selected.x + dx
   if new_x < 1 then
      new_x = 1
      return
   end
   if new_x > self.grid.width then
      new_x = self.grid.width
      return
   end

   local new_y = self.selected.y + dy
   if new_y < 1 then
      new_y = 1
      return
   end
   if new_y > self.grid.height then
      new_y = self.grid.height
      return
   end

   local new_selected = Pt:new(new_x, new_y)

   trace('sels: ' .. tostring(self.selected) .. ' ' .. tostring(new_selected) )

   if self.input_mode == InputModes.Select then
      self.selected = new_selected
   elseif self.input_mode == InputModes.Swap then
      self.input_mode = InputModes.Select

      local ret = self.grid:allow_swap(self.selected, new_selected)
      local allowed = ret[1]
      local matches = ret[2]
      trace('allow?: ' .. tostring(allowed) .. ' ' .. tostring(matches))
      if allowed then
	 self.grid:swap(self.selected, new_selected)
	 for i, m in pairs(matches) do
	    table.insert(self.particles, new_part(m))
	 end
	 self.grid:remove_matches(matches)
	 self.events:emit('bullet', 0)
      end
      self.selected=new_selected
   else
      -- error
   end
end

function M3_Game:move_up ()
   self:select_tile(0, -1)
end

function M3_Game:move_down ()
   self:select_tile(0, 1)
end

function M3_Game:move_left ()
  self:select_tile(-1, 0)
end

function M3_Game:move_right ()
   self:select_tile(1, 0)
end

function mod(a, b)
   return a - math.floor(a/b)*b
end

function M3_Game:draw ()
   self:grid_draw()
   if #self.particles > 0 then
      trace('drawing m3 particles: ' .. #self.particles)
      for i, m in pairs(self.particles) do
	 local orig_x = (m.x-1)*TILE_SIZE
	 local orig_y = (m.y-1)*TILE_SIZE
	 local part_num =  mod(m.life, #part_sprs)
	 local tile_grp = part_sprs[m.life]
	 --trace(tile .. " " .. tile_grp)
	 spr(tile_grp, orig_x+120, orig_y, -1, 1, 0, 0,2,2)
	 m.life = m.life -1
	 if m.life == 0 then
	    table.remove(self.particles, i)
	 end
      end
   end
end

function M3_Game:init (events)
   self.events = events
   self.grid:init(6)
   self.grid:test()
   local clean = self.grid:find_matches()
   if #clean then
      self.grid:remove_matches(clean)
   end
   self.grid:test()
end
-- END m3_lib.lua

-- BEGIN main.lua

-- Game States
GameStates = Enum("StartScreen", "Playing", "GameOver")
current_state = GameStates.StartScreen

mc = {}
m3 = {}
events = Events:new()

function TIC()
    handle_input()
    
    if current_state == GameStates.StartScreen then
        draw_start_screen()
    elseif current_state == GameStates.Playing then
        mc:update()
        cls(0)
        mc:draw()
        m3:draw()
    end
end

function draw_start_screen()
   cls(0)
   
   -- Draw title using text
   local title = "BUBBLE REACTOR DEFENCE"
   local title_x = 120 - (#title * 6) // 2
   print(title, title_x, 40, 12)
   
   -- Draw subtitle
   local subtitle = "Match-3 meets Missile Command"
   local subtitle_x = 120 - (#subtitle * 6) // 2
   print(subtitle, subtitle_x, 60, 6)
   
   -- Draw instructions
   print("Use arrow keys to move", 60, 90, 15)
   print("Press Z to select/swap", 60, 100, 15)
   print("Match 3+ tiles to fire!", 60, 110, 15)
   
   -- Draw start prompt (with blinking effect)
   if math.floor(time() / 500) % 2 == 0 then
      local start_text = "PRESS Z TO START"
      local start_x = 120 - (#start_text * 6) // 2
      print(start_text, start_x, 130, 14)
   end
end

function start_game()
   current_state = GameStates.Playing
   mc = MC_Game:new()
   m3 = M3_Game:new()
   mc:init(events)
   m3:init(events)
end

function BOOT()
   current_state = GameStates.StartScreen
end

-- Handle input
function handle_input()
    if current_state == GameStates.StartScreen then
        if btnp(4) then -- Z key to start
            start_game()
        end
    elseif current_state == GameStates.Playing then
        if btnp(0) then -- Up
            m3:move_up()
        elseif btnp(1) then -- Down
            m3:move_down()
        elseif btnp(2) then -- Left
            m3:move_left()
        elseif btnp(3) then -- Right
            m3:move_right()
        elseif btnp(4) then -- Select -- Z
            if m3.input_mode == InputModes.Select then
                m3.input_mode = InputModes.Swap
            else
                m3.input_mode = InputModes.Select
            end
        end
    end
end
-- END main.lua

-- <TILES>
-- 000:4444444433344433333434424234334444433044343332423242332432443444
-- 002:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
-- 003:0000000000000000000000003340433003444300034443000344430000444000
-- 005:0000000000000d00000c000000000000000000000000000000000c0000000000
-- 006:000000000000000000000c000000000000c00000000000000000000000000000
-- 007:00000000000d000000dcd000000d00000000000000000d000000dcd000000d00
-- 008:0000000000000d000000dcd000d00d000dcd000000d000000000000000000000
-- 009:000d000000dcd0000dcccd0000dcd000000d0d000000dcd0000dcccd0000dcd0
-- 010:00000d000000dcd000ddcccd0dcddcd0dcccdd000dcd000000d0000000000000
-- 011:00dcd0000dcccd00dcccccd00dcccd0000dcdcdd000dcccd00dccccc000dcccd
-- 012:0000dcd000ddcccd0dccccccdccccccdccccccd0dcccdd00ddcd0000d00000d0
-- 016:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeebebbbbedeeeebbedededeeeeeeeee
-- 017:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbebeebbeededeebdedededeeeeeeeee
-- 018:bbbbbbbbbbbbbbbbbbbbbbbbbbb6bbbbb6b6b6bbbb6666bbbbb6bbbbbbb6bbbb
-- 019:e0ccc0e00eeeee0000e4e00000e4e00000e4e00000e4e00000eee000000e0000
-- 021:000000000000000000000c0000000000000000000000000000000000000000c0
-- 022:0000000000000000000000c0000000000000000000c000000000000000000000
-- 023:00000000000000d000000dcd000000d00000000000000d000000dcd000000d00
-- 024:00000000000000d000000dcd000000d000d000000dcd000000d0000000000000
-- 025:00000dd000000dcd0000dccc00000dcd00000dd00000dcd0000dcccd0000dcd0
-- 026:000000d000000dcdd000dccc00d00dcd0dcd00d0dcccd0000dcd000000d00000
-- 027:0000dccd0000dccc000dcccc0000dccc0000dccd000dcccd00dccccc000dcccd
-- 028:00000dcdd000dccccd0dccccddcddcccdcccddcdcccccdd0dcccd0000dcd0000
-- 066:0000000000000000000000000004400000044000000000000000000000000000
-- 067:0000000000000000000330000034433003344300000330000000000000000000
-- 068:000300000033330003444433034cc430334cc430034444300033330000003000
-- 160:0000000000000004000000040000004400000044000044440444444c004444c4
-- 161:000000004000000040000000440000004400000044440000c44444404c444400
-- 162:000000000fffffff0fffffff0ffeeeee0ffeffff0ffeffff0ffeffff0ffeffff
-- 163:00000000fffffff0fffffff0eeeeeff0fffffff0fffffff0fffffff0fffffff0
-- 176:000044c4000004c40000044c0000444400004444000444400044400000000000
-- 177:4c4400004c400000c44000004444000044440000044440000004440000000000
-- 178:0ffeffff0ffeffff0ffeffff0ffeffff0ffeffff0fffffff0fffffff00000000
-- 179:fffffff0fffffff0fffffff0fffffff0fffffff0fffffff0fffffff000000000
-- 192:0000000000022200002222200222222202222222022222220222222200222222
-- 193:0000000000222000022222002222222022222220222212202222122022221200
-- 194:0000000000000006000000660000066600006665000666560066656606665666
-- 195:0000000060000000660000006660000056660000656660006656660066656660
-- 208:0022222200022222000222220000222200000222000000220000000200000000
-- 209:2221220022212000221220002122000012200000220000002000000000000000
-- 210:0665666600666666000666660000666600000666000000660000000600000000
-- 211:6666566066666600666660006666000066600000660000006000000000000000
-- 213:ccccccccc0000000c0000000c0000000c0000000c0000000c0000000c0000000
-- 214:cccccccc00000000000000000000000000000000000000000000000000000000
-- 215:cccccccc0000000c0000000c0000000c0000000c0000000c0000000c0000000c
-- 224:00000000000000aa0000aaaa000aaaab00aaaaba00aaabaa0aaabaaa0aabaaaa
-- 225:00000000aa000000aaaa0000baaaa000aaaaaa00aaaaaa00aaaaaaa0aaaaaaa0
-- 226:0000000000000003000000030000003300000033000003340000034300003343
-- 227:0000000030000000300000003300000033000000433000003330000033330000
-- 229:c0000000c0000000c0000000c0000000c0000000c0000000c0000000c0000000
-- 231:0000000c0000000c0000000c0000000c0000000c0000000c0000000c0000000c
-- 240:0aabaaaa0aaaaaaa00aaaaaa00aaaaaa000aaaaa0000aaaa000000aa00000000
-- 241:aaaaaaa0aaaaaaa0aaaaaa00aaaaaa00aaaaa000aaaa0000aa00000000000000
-- 242:0000343300033433000343330033433300333333033333330333333300000000
-- 243:3333000033333000333330003333330033333300333333303333333000000000
-- 245:c0000000c0000000c0000000c0000000c0000000c0000000c0000000cccccccc
-- 246:00000000000000000000000000000000000000000000000000000000cccccccc
-- 247:0000000c0000000c0000000c0000000c0000000c0000000c0000000ccccccccc
-- </TILES>

-- <MAP>
-- 000:202020202020202020202020202020101010101010101010101010101010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
-- 001:202020202020202020202020202020101010101010101010101010101010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
-- 002:202020202020202020202020202020101010101010101010101010101010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
-- 003:202020202020202020202020202020101010101010101010101010101010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
-- 004:202020202020202020202020202020101010101010101010101010101010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
-- 005:202020202020202020202020202020101010101010101010101010101010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
-- 006:202020202020202020202020202020101010101010101010101010101010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
-- 007:202020202020202020202020202020101010101010101010101010101010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
-- 008:202020202020202020202020202020101010101010101010101010101010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
-- 009:202020202020202020202020202020101010101010101010101010101010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
-- 010:202020202020202020202020202020101010101010101010101010101010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
-- 011:202020202020202020202020202020101010101010101010101010101010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
-- 012:202020202020202020202020202020101010101010101010101010101010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
-- 013:202020202020202020202020202020101010101010101010101010101010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
-- 014:202020202020202020202020202020101010101010101010101010101010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
-- 015:200111202021110120202120111120101010101010101010101010101010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
-- 016:000000000000000000000000000000101010101010101010101010101010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
-- </MAP>

-- <WAVES>
-- 000:00000000ffffffff00000000ffffffff
-- 001:0123456789abcdeffedcba9876543210
-- 002:0123456789abcdef0123456789abcdef
-- </WAVES>

-- <SFX>
-- 000:000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000304000000000
-- </SFX>

-- <TRACKS>
-- 000:100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
-- </TRACKS>

-- <PALETTE>
-- 000:1a1c2c5d275db13e53ef7d57ffcd75a7f07038b76425717929366f3b5dc941a6f673eff7f4f4f494b0c2566c86333c57
-- </PALETTE>
